name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-linux-cross:
    name: Build for Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ stable ]
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      - name: Checking out sources
        uses: actions/checkout@v3
      - name: Running cross build
        if: matrix.target != 'x86_64-unknown-linux-gnu'
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          toolchain: ${{ matrix.rust }}
          args: --release --target ${{ matrix.target }}
      - name: Running cargo build
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: ${{ matrix.rust }}
          args: --release

